feat(AU-2115): use ATLAS_OPTIONS for pull_translations command
openedx/frontend-app-ora pull request #225
Opened 2024-07-03 00:33 UTC by Rodra

2024-07-03 07:19 UTC, brian-smith-tcril requested changes
Great catch! Thank you so much for this PR!

It seems the CI failure is [unrelated to this PR](https://github.com/openedx/frontend-app-ora/actions/runs/9738041863/job/26871007172) so we can disregard that.

I would like to request the changes to the `.json` files in `src/i18n/messages` be reverted, as those files are pulled from the `openedx-translations` repo via `atlas` at build time instead.

2024-07-03 14:13 UTC, brian-smith-tcril approved these changes

2024-07-03 14:20 UTC, Rodra commented
@brian-smith-tcril  thank you for jumping in and check my PR. I'm not familiar with the fork process here, how can I get this merged ?

2024-07-08 14:25 UTC, Rodra commented
@brian-smith-tcril still waiting for this to be merged since I don't have write access.

2024-07-18 14:07 UTC, merged